### ISSUE TITLE
Lazy parameter

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#24]
A missing functionality of pymontecarlo is the ability to use other parameters of an option to define a new one. For instance, it should be possible to easily set the maximum energy of an ED spectrum to the beam energy. I propose to create the following interface:

```
class Lazy:

    def resolve(self, options):
        raise NotImplementedError
```

Upon the creation of an *Options* object, the `resolve` method should be called.

**Comment by ppinard** [comment]
@drix00 said:
Maybe have a look at lmfit code how it deal with parameters and equation of parameters in the fit model and constraints which is similar to what we need pymontecarlo to do.

**Comment by ppinard** [comment]
I know the lmfit special syntax, but I must admit I don't really like using strings to define relationships between objects. [sympy](http://docs.sympy.org/latest/tutorial/basic_operations.html) seems to have a more sophisticated way to handle this.

**Comment by drix00** [comment]
I was talking more about the combination of models to create new model and using the suffix/prefix to have different variable. Also I have implemented for pymcxray sample creation that depend of parameters resulting from the range. As example, I have a range of thickness and a range of composition for each combination of these I create a different sample.

We can have three types of options:

- Fixed with only one value
- Varied with a range/list of values
- Determined by a function using the other parameters as input (fixed and varied).

My implementation was very simple using a dictionary and specific key for each parameter. But I think it could be implemented for any parameter using a parser.

**Comment by ppinard** [comment]
I do not think this applies anymore.
