### ISSUE TITLE
Branching model

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#52]
What's the idea behind pymontecarlos branching model? When I want to set up a productive system, which is the best source to get a stable and up to date version of pymontecarlo? Can I simply go with the packages provided on PyPI or are they outdated?

**Comment by ppinard** [comment]
Right now there is only the master branch. There hasn't been any stable release since 1.0 (the one on PyPI), but I think many of the features you are looking for are only in the master branch. There will be a new release when the issues in the [2.0 milestone](https://github.com/pymontecarlo/pymontecarlo/milestone/2) are completed

**Comment by 0b11001111** [comment]
Okay, I'll talk to @silrichter what we do next but I think it's best to get the current version running to work with latest features and then switch to the stable version once 2.0 is out.
